# 应用名称
spring:
  application:
    name: provider-service-3

# 服务器端口
server:
  port: 8083

# Dubbo配置
dubbo:
  application:
    name: provider-service-3
  registry:
    address: nacos://localhost:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: 20883  # 不同的端口
  scan:
    base-packages: com.example.dubbo.provider.service
