# 应用名称
spring:
  application:
    name: provider-service-1

# 服务器端口
server:
  port: 8081

# Dubbo配置
dubbo:
  # 应用配置
  application:
    name: provider-service-1
  # 注册中心配置
  registry:
    address: nacos://localhost:8848  # Nacos服务器地址
    username: nacos                   # Nacos用户名
    password: nacos                   # Nacos密码
  # 协议配置
  protocol:
    name: dubbo
    port: 20881                       # 服务端口，每个提供者需要不同
  # 扫描注解的包
  scan:
    base-packages: com.example.dubbo.provider.service
