# 应用名称
spring:
  application:
    name: provider-hello-12

# 服务器端口
server:
  port: 8083

# Dubbo配置
dubbo:
  application:
    name: hello-service
    register-mode: instance
  registry:
    address: nacos://localhost:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: -1  # 不同的端口
  scan:
    base-packages: com.example.dubbo.provider.service.hello
